name:                denomusic
version:             0.1.0.0
github:              "githubuser/denomusic"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"
language:            GHC2021

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/denomusic#readme>

dependencies:
- base >= 4.7 && < 5
- Euterpea
- checkers
- QuickCheck
- split
- containers
- step-function
- hspec
- mtl
- transformers
- random
- lens
- fingertree
- dual-tree
- monoid-extras
- linear
- recursion-schemes
- deepseq
- lilypond
- prettify
- process
- MemoTrie
- async

default-extensions: []

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
