name:                denomusic
version:             0.1.0.0
github:              "isovector/denomusic"
license:             BSD-3-Clause
author:              "Sandy Maguire"
maintainer:          "music@sandymaguire.me"
copyright:           "2025 Sandy Maguire"
language:            GHC2021

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/denomusic#readme>

dependencies:
- base >= 4.7 && < 5
- Euterpea
- checkers
- QuickCheck
- containers >= 0.5.9
- monoidal-containers
- hspec
- mtl
- transformers
- lens
- fingertree
- recursion-schemes
- deepseq
- lilypond
- pretty
- process
- groups
- step-function
- profunctors

default-extensions:
- DerivingStrategies
- DerivingVia
- TypeFamilies
- LambdaCase
- ViewPatterns
- PatternSynonyms

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
